const A='http://localhost:8090/api';
const post=(token,o)=>fetch(A,{method:'POST',body:JSON.stringify({token,...o})}).then(r=>r.json());
const kisa=o=>JSON.stringify(o).slice(0,230);
(async()=>{
 const Y='test:yonetim@ornek.com', K='test:elektromobil@ornek.com', R='test:roket@ornek.com', X='test:yabanci@test.com';
 console.log('1 yabancı:', kisa(await post(X,{islem:'oturum'})));
 console.log('2 tokensiz:', kisa(await post('',{islem:'oturum'})));
 console.log('3 kaptan oturum:', kisa(await post(K,{islem:'oturum'})));
 const b=await post(K,{islem:'basvurular'}); console.log('4 kaptan başvuru sayısı:', b.liste.length, 'hepsi elektromobil mi:', b.liste.every(x=>x.mulakatlar.every(m=>m.takim==='Elektromobil')));
 const by=await post(Y,{islem:'basvurular'}); console.log('5 yönetici başvuru:', by.liste.length);
 const d=await post(K,{islem:'basvuru',kod:b.liste[0].kod}); console.log('6 detay:', d.ad, d.cevaplar.length,'cevap', kisa(d.cevaplar.slice(0,3)));
 const baska=by.liste.find(x=>!x.takimlar.includes('Elektromobil'));
 console.log('7 yetkisiz detay:', kisa(await post(K,{islem:'basvuru',kod:baska.kod})));
 const g=await post(K,{islem:'gruplar'}); console.log('8 gruplar:', kisa(g));
 console.log('9 roket kaptanı grup görür mü:', (await post(R,{islem:'gruplar'})).gruplar.length);
 const plan={tarih:'15.10.2026',baslangic:'10:00',bitis:'17:00',aralik:'10',ogle:'',yer:'B Blok Z-12',konum:''};
 console.log('10 önizleme hata:', kisa(await post(K,{islem:'planOnizle',grup:1,plan})));
 plan.tarih='15.10.2026, 16.10.2026';
 const on=await post(K,{islem:'planOnizle',grup:1,plan}); console.log('11 önizleme:', on.ilk,'→',on.son, on.liste.length);
 console.log('12 roket kaptanı elektromobil planı:', kisa(await post(R,{islem:'planKaydet',grup:1,plan})));
 console.log('13 kaydet:', kisa(await post(K,{islem:'planKaydet',grup:1,plan})));
 console.log('14 kaptan onaylayamaz:', kisa(await post(K,{islem:'planOnayla',grup:1})));
 let m=await fetch('http://localhost:8090/mails').then(r=>r.json()); console.log('15 yöneticiye onay maili:', m.at(-1).to, '|', m.at(-1).subject);
 const once=m.length;
 console.log('16 yönetici onay:', kisa(await post(Y,{islem:'planOnayla',grup:1})));
 m=await fetch('http://localhost:8090/mails').then(r=>r.json()); console.log('17 giden mülakat maili:', m.length-once, '|', m.at(-1).subject);
 console.log('18 tekrar onay:', kisa(await post(Y,{islem:'planOnayla',grup:1})));
 const g2=await post(K,{islem:'gruplar'}); console.log('19 grup durumu:', g2.gruplar[0].durum, g2.gruplar[0].mail);
 const kod=b.liste[0].kod;
 console.log('20 durum sorgu:', kisa(await fetch(A+'?islem=durum&kod='+kod).then(r=>r.json())));
 console.log('21 giriş roket kaptanı:', kisa(await post(R,{islem:'giris',kod})));
 console.log('22 giriş:', kisa(await post(K,{islem:'giris',kod})));
 console.log('23 tekrar giriş:', kisa(await post(K,{islem:'giris',kod})));
 console.log('24 sonuç kaydet:', kisa(await post(K,{islem:'sonucKaydet',kod,takim:'Elektromobil',sonuc:'Kabul'})));
 const kod2=b.liste[1].kod; await post(K,{islem:'sonucKaydet',kod:kod2,takim:'Elektromobil',sonuc:'Ret'});
 console.log('25 onaya gönder:', kisa(await post(K,{islem:'sonucOnayaGonder',takim:'Elektromobil'})));
 console.log('26 kaptan sonuç onaylayamaz:', kisa(await post(K,{islem:'sonucOnayla',takim:'Elektromobil'})));
 console.log('27 onaydayken değiştir:', kisa(await post(K,{islem:'sonucKaydet',kod,takim:'Elektromobil',sonuc:'Yedek'})));
 await post(K,{islem:'sonucKaydet',kod,takim:'Elektromobil',sonuc:'Kabul'}); await post(K,{islem:'sonucOnayaGonder',takim:'Elektromobil'});
 const o2=(await fetch('http://localhost:8090/mails').then(r=>r.json())).length;
 console.log('28 yönetici sonuç onay:', kisa(await post(Y,{islem:'sonucOnayla',takim:'Elektromobil'})));
 m=await fetch('http://localhost:8090/mails').then(r=>r.json()); console.log('29 sonuç mailleri:', m.slice(o2).map(x=>x.subject).join(' || '));
 console.log('30 gönderildikten sonra değiştir:', kisa(await post(K,{islem:'sonucKaydet',kod,takim:'Elektromobil',sonuc:'Ret'})));
 console.log('31 durum sonuç:', kisa(await fetch(A+'?islem=durum&kod='+kod).then(r=>r.json())));
 const gr=await post(Y,{islem:'gruplar'}); console.log('32 grupsuz:', kisa(gr.grupsuz));
 const ilk=gr.grupsuz[0]; console.log('33 kalanlardan grup:', kisa(await post(Y,{islem:'grupOlustur',takim:ilk.takim,tur:ilk.tur})));
})();
